- dashboard: yami_test
  title: Untitled Visualization
  model: haylen_pruebasmtr
  explore: order_items
  type: looker_scatter
  fields: [order_items.id, order_items.phone, order_items.returned_date, order_items.count]
  sorts: [order_items.returned_date desc]
  limit: 500
  x_axis_gridlines: false
  y_axis_gridlines: true
  show_view_names: false
  show_y_axis_labels: true
  show_y_axis_ticks: true
  y_axis_tick_density: default
  y_axis_tick_density_custom: 5
  show_x_axis_label: true
  show_x_axis_ticks: true
  y_axis_scale_mode: linear
  x_axis_reversed: false
  y_axis_reversed: false
  plot_size_by_field: false
  trellis: ''
  stacking: ''
  limit_displayed_rows: false
  legend_position: center
  point_style: none
  show_value_labels: false
  label_density: 25
  x_axis_scale: auto
  y_axis_combined: true
  show_null_points: true
  show_row_numbers: true
  truncate_column_names: false
  hide_totals: false
  hide_row_totals: false
  table_theme: editable
  enable_conditional_formatting: false
  conditional_formatting_include_totals: false
  conditional_formatting_include_nulls: false
  defaults_version: 1
  series_types: {}
  ordering: none
  show_null_labels: false
  show_totals_labels: false
  show_silhouette: false
  totals_color: "#808080"
  transpose: false
  truncate_text: true
  size_to_fit: true
  header_text_alignment: left
  header_font_size: 12
  rows_font_size: 12
